version: "3.8"

services:
  webhook:
    build:
      context: .
      dockerfile: Dockerfile
    image: matrix-webhook:latest
    container_name: matrix_webhook
    restart: unless-stopped
    env_file:
      - .env
